server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vite-project
    username: myuser 
    password: mypassword

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
