server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vite-project
    username: myuser 
    password: mypassword

security:
  jwt:
    secret-key: "3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b"
    expiration-time: 3600000 # 1 hour in milliseconds
management:
    endpoints:
        web:
        exposure:
            include: "*"
