server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vite-project
    username: myuser 
    password: mypassword

security:
  jwt:
    secret-key: "3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b"
    expiration-time: 3600000 # 1 hour in milliseconds
management:
  endpoint:
    info:
      env:
        enabled: true
  endpoints:
      web:
        exposure:
          include: "*"


info:
  app:
    name: "Expense Service"
    description: "Expense Service description"
    version: "1.0"
  
contact:
  name: addoumi
  sexe: male
  age: 31

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
